import { Transaction } from '@prisma/client';

export const data: Transaction[] = [
  {
    transactionId: 'transaction_1',
    description: 'Transaction 1',
    amount: 86203,
    fromAccount: 'account_3',
    toAccount: 'account_6',
    transactionDate: '2023-05-24',
  },
  {
    transactionId: 'transaction_2',
    description: 'Transaction 2',
    amount: 71532,
    fromAccount: 'account_4',
    toAccount: 'account_6',
    transactionDate: '2023-04-15',
  },
  {
    transactionId: 'transaction_3',
    description: 'Transaction 3',
    amount: 44139,
    fromAccount: 'account_5',
    toAccount: 'account_6',
    transactionDate: '2023-10-09',
  },
  {
    transactionId: 'transaction_4',
    description: 'Transaction 4',
    amount: 24584,
    fromAccount: 'account_5',
    toAccount: 'account_6',
    transactionDate: '2023-08-27',
  },
  {
    transactionId: 'transaction_5',
    description: 'Transaction 5',
    amount: 62898,
    fromAccount: 'account_1',
    toAccount: 'account_5',
    transactionDate: '2023-04-21',
  },
  {
    transactionId: 'transaction_6',
    description: 'Transaction 6',
    amount: 16458,
    fromAccount: 'account_1',
    toAccount: 'account_3',
    transactionDate: '2023-11-11',
  },
  {
    transactionId: 'transaction_7',
    description: 'Transaction 7',
    amount: 34359,
    fromAccount: 'account_1',
    toAccount: 'account_4',
    transactionDate: '2023-09-22',
  },
  {
    transactionId: 'transaction_8',
    description: 'Transaction 8',
    amount: 62131,
    fromAccount: 'account_4',
    toAccount: 'account_2',
    transactionDate: '2023-07-12',
  },
  {
    transactionId: 'transaction_9',
    description: 'Transaction 9',
    amount: 25131,
    fromAccount: 'account_1',
    toAccount: 'account_2',
    transactionDate: '2023-02-20',
  },
  {
    transactionId: 'transaction_10',
    description: 'Transaction 10',
    amount: 98324,
    fromAccount: 'account_1',
    toAccount: 'account_2',
    transactionDate: '2023-08-17',
  },
  {
    transactionId: 'transaction_11',
    description: 'Transaction 11',
    amount: 24962,
    fromAccount: 'account_5',
    toAccount: 'account_3',
    transactionDate: '2023-04-09',
  },
  {
    transactionId: 'transaction_12',
    description: 'Transaction 12',
    amount: 2932,
    fromAccount: 'account_4',
    toAccount: 'account_5',
    transactionDate: '2023-05-31',
  },
  {
    transactionId: 'transaction_13',
    description: 'Transaction 13',
    amount: 10246,
    fromAccount: 'account_2',
    toAccount: 'account_3',
    transactionDate: '2023-07-14',
  },
  {
    transactionId: 'transaction_14',
    description: 'Transaction 14',
    amount: 88019,
    fromAccount: 'account_5',
    toAccount: 'account_2',
    transactionDate: '2023-09-11',
  },
  {
    transactionId: 'transaction_15',
    description: 'Transaction 15',
    amount: 85146,
    fromAccount: 'account_2',
    toAccount: 'account_4',
    transactionDate: '2023-11-05',
  },
  {
    transactionId: 'transaction_16',
    description: 'Transaction 16',
    amount: 66002,
    fromAccount: 'account_1',
    toAccount: 'account_3',
    transactionDate: '2023-01-26',
  },
  {
    transactionId: 'transaction_17',
    description: 'Transaction 17',
    amount: 71762,
    fromAccount: 'account_1',
    toAccount: 'account_5',
    transactionDate: '2023-08-27',
  },
  {
    transactionId: 'transaction_18',
    description: 'Transaction 18',
    amount: 24142,
    fromAccount: 'account_6',
    toAccount: 'account_3',
    transactionDate: '2023-07-06',
  },
  {
    transactionId: 'transaction_19',
    description: 'Transaction 19',
    amount: 30552,
    fromAccount: 'account_1',
    toAccount: 'account_4',
    transactionDate: '2023-01-22',
  },
  {
    transactionId: 'transaction_20',
    description: 'Transaction 20',
    amount: 45313,
    fromAccount: 'account_3',
    toAccount: 'account_6',
    transactionDate: '2023-05-11',
  },
  {
    transactionId: 'transaction_21',
    description: 'Transaction 21',
    amount: 93012,
    fromAccount: 'account_5',
    toAccount: 'account_4',
    transactionDate: '2023-03-13',
  },
  {
    transactionId: 'transaction_22',
    description: 'Transaction 22',
    amount: 41762,
    fromAccount: 'account_5',
    toAccount: 'account_1',
    transactionDate: '2023-03-20',
  },
  {
    transactionId: 'transaction_23',
    description: 'Transaction 23',
    amount: 34927,
    fromAccount: 'account_4',
    toAccount: 'account_2',
    transactionDate: '2023-05-13',
  },
  {
    transactionId: 'transaction_24',
    description: 'Transaction 24',
    amount: 56165,
    fromAccount: 'account_4',
    toAccount: 'account_6',
    transactionDate: '2023-06-06',
  },
  {
    transactionId: 'transaction_25',
    description: 'Transaction 25',
    amount: 71366,
    fromAccount: 'account_6',
    toAccount: 'account_3',
    transactionDate: '2023-09-04',
  },
  {
    transactionId: 'transaction_26',
    description: 'Transaction 26',
    amount: 5370,
    fromAccount: 'account_1',
    toAccount: 'account_4',
    transactionDate: '2023-10-20',
  },
  {
    transactionId: 'transaction_27',
    description: 'Transaction 27',
    amount: 54833,
    fromAccount: 'account_6',
    toAccount: 'account_4',
    transactionDate: '2023-06-25',
  },
  {
    transactionId: 'transaction_28',
    description: 'Transaction 28',
    amount: 11113,
    fromAccount: 'account_3',
    toAccount: 'account_5',
    transactionDate: '2023-09-24',
  },
  {
    transactionId: 'transaction_29',
    description: 'Transaction 29',
    amount: 24653,
    fromAccount: 'account_1',
    toAccount: 'account_3',
    transactionDate: '2023-05-23',
  },
  {
    transactionId: 'transaction_30',
    description: 'Transaction 30',
    amount: 55907,
    fromAccount: 'account_2',
    toAccount: 'account_6',
    transactionDate: '2023-02-25',
  },
  {
    transactionId: 'transaction_31',
    description: 'Transaction 31',
    amount: 63091,
    fromAccount: 'account_2',
    toAccount: 'account_5',
    transactionDate: '2023-03-06',
  },
  {
    transactionId: 'transaction_32',
    description: 'Transaction 32',
    amount: 30793,
    fromAccount: 'account_3',
    toAccount: 'account_2',
    transactionDate: '2023-01-12',
  },
  {
    transactionId: 'transaction_33',
    description: 'Transaction 33',
    amount: 37426,
    fromAccount: 'account_2',
    toAccount: 'account_5',
    transactionDate: '2023-08-31',
  },
  {
    transactionId: 'transaction_34',
    description: 'Transaction 34',
    amount: 15292,
    fromAccount: 'account_4',
    toAccount: 'account_3',
    transactionDate: '2023-02-14',
  },
  {
    transactionId: 'transaction_35',
    description: 'Transaction 35',
    amount: 88795,
    fromAccount: 'account_6',
    toAccount: 'account_1',
    transactionDate: '2023-10-25',
  },
  {
    transactionId: 'transaction_36',
    description: 'Transaction 36',
    amount: 20312,
    fromAccount: 'account_1',
    toAccount: 'account_2',
    transactionDate: '2023-07-03',
  },
  {
    transactionId: 'transaction_37',
    description: 'Transaction 37',
    amount: 74514,
    fromAccount: 'account_4',
    toAccount: 'account_6',
    transactionDate: '2023-05-16',
  },
  {
    transactionId: 'transaction_38',
    description: 'Transaction 38',
    amount: 11063,
    fromAccount: 'account_4',
    toAccount: 'account_6',
    transactionDate: '2023-11-06',
  },
  {
    transactionId: 'transaction_39',
    description: 'Transaction 39',
    amount: 95139,
    fromAccount: 'account_2',
    toAccount: 'account_1',
    transactionDate: '2023-04-22',
  },
  {
    transactionId: 'transaction_40',
    description: 'Transaction 40',
    amount: 72138,
    fromAccount: 'account_5',
    toAccount: 'account_2',
    transactionDate: '2023-01-29',
  },
  {
    transactionId: 'transaction_41',
    description: 'Transaction 41',
    amount: 92546,
    fromAccount: 'account_1',
    toAccount: 'account_4',
    transactionDate: '2023-11-11',
  },
  {
    transactionId: 'transaction_42',
    description: 'Transaction 42',
    amount: 81660,
    fromAccount: 'account_6',
    toAccount: 'account_2',
    transactionDate: '2023-07-05',
  },
  {
    transactionId: 'transaction_43',
    description: 'Transaction 43',
    amount: 12041,
    fromAccount: 'account_6',
    toAccount: 'account_4',
    transactionDate: '2023-02-25',
  },
  {
    transactionId: 'transaction_44',
    description: 'Transaction 44',
    amount: 84584,
    fromAccount: 'account_2',
    toAccount: 'account_5',
    transactionDate: '2023-11-14',
  },
  {
    transactionId: 'transaction_45',
    description: 'Transaction 45',
    amount: 7046,
    fromAccount: 'account_2',
    toAccount: 'account_1',
    transactionDate: '2023-07-12',
  },
  {
    transactionId: 'transaction_46',
    description: 'Transaction 46',
    amount: 78287,
    fromAccount: 'account_6',
    toAccount: 'account_4',
    transactionDate: '2023-02-21',
  },
  {
    transactionId: 'transaction_47',
    description: 'Transaction 47',
    amount: 57914,
    fromAccount: 'account_6',
    toAccount: 'account_2',
    transactionDate: '2023-11-03',
  },
  {
    transactionId: 'transaction_48',
    description: 'Transaction 48',
    amount: 90964,
    fromAccount: 'account_3',
    toAccount: 'account_5',
    transactionDate: '2023-09-05',
  },
  {
    transactionId: 'transaction_49',
    description: 'Transaction 49',
    amount: 27460,
    fromAccount: 'account_6',
    toAccount: 'account_2',
    transactionDate: '2023-02-12',
  },
  {
    transactionId: 'transaction_50',
    description: 'Transaction 50',
    amount: 78505,
    fromAccount: 'account_3',
    toAccount: 'account_1',
    transactionDate: '2023-06-10',
  },
  {
    transactionId: 'transaction_51',
    description: 'Transaction 51',
    amount: 59451,
    fromAccount: 'account_2',
    toAccount: 'account_3',
    transactionDate: '2023-08-23',
  },
  {
    transactionId: 'transaction_52',
    description: 'Transaction 52',
    amount: 30856,
    fromAccount: 'account_5',
    toAccount: 'account_1',
    transactionDate: '2023-09-20',
  },
  {
    transactionId: 'transaction_53',
    description: 'Transaction 53',
    amount: 58267,
    fromAccount: 'account_5',
    toAccount: 'account_2',
    transactionDate: '2023-04-01',
  },
  {
    transactionId: 'transaction_54',
    description: 'Transaction 54',
    amount: 8562,
    fromAccount: 'account_1',
    toAccount: 'account_2',
    transactionDate: '2023-11-07',
  },
  {
    transactionId: 'transaction_55',
    description: 'Transaction 55',
    amount: 75337,
    fromAccount: 'account_3',
    toAccount: 'account_1',
    transactionDate: '2023-07-26',
  },
  {
    transactionId: 'transaction_56',
    description: 'Transaction 56',
    amount: 45232,
    fromAccount: 'account_1',
    toAccount: 'account_3',
    transactionDate: '2023-06-10',
  },
  {
    transactionId: 'transaction_57',
    description: 'Transaction 57',
    amount: 19315,
    fromAccount: 'account_6',
    toAccount: 'account_3',
    transactionDate: '2023-07-02',
  },
  {
    transactionId: 'transaction_58',
    description: 'Transaction 58',
    amount: 26769,
    fromAccount: 'account_2',
    toAccount: 'account_4',
    transactionDate: '2023-07-13',
  },
  {
    transactionId: 'transaction_59',
    description: 'Transaction 59',
    amount: 49532,
    fromAccount: 'account_3',
    toAccount: 'account_5',
    transactionDate: '2023-08-18',
  },
  {
    transactionId: 'transaction_60',
    description: 'Transaction 60',
    amount: 16829,
    fromAccount: 'account_2',
    toAccount: 'account_1',
    transactionDate: '2023-07-21',
  },
  {
    transactionId: 'transaction_61',
    description: 'Transaction 61',
    amount: 6794,
    fromAccount: 'account_6',
    toAccount: 'account_5',
    transactionDate: '2023-05-21',
  },
  {
    transactionId: 'transaction_62',
    description: 'Transaction 62',
    amount: 56623,
    fromAccount: 'account_2',
    toAccount: 'account_5',
    transactionDate: '2023-05-31',
  },
  {
    transactionId: 'transaction_63',
    description: 'Transaction 63',
    amount: 16662,
    fromAccount: 'account_5',
    toAccount: 'account_6',
    transactionDate: '2023-08-14',
  },
  {
    transactionId: 'transaction_64',
    description: 'Transaction 64',
    amount: 10791,
    fromAccount: 'account_4',
    toAccount: 'account_3',
    transactionDate: '2023-11-08',
  },
  {
    transactionId: 'transaction_65',
    description: 'Transaction 65',
    amount: 17795,
    fromAccount: 'account_6',
    toAccount: 'account_1',
    transactionDate: '2023-11-09',
  },
  {
    transactionId: 'transaction_66',
    description: 'Transaction 66',
    amount: 33221,
    fromAccount: 'account_4',
    toAccount: 'account_6',
    transactionDate: '2023-10-22',
  },
  {
    transactionId: 'transaction_67',
    description: 'Transaction 67',
    amount: 6277,
    fromAccount: 'account_2',
    toAccount: 'account_6',
    transactionDate: '2023-07-10',
  },
  {
    transactionId: 'transaction_68',
    description: 'Transaction 68',
    amount: 6247,
    fromAccount: 'account_3',
    toAccount: 'account_6',
    transactionDate: '2023-10-06',
  },
  {
    transactionId: 'transaction_69',
    description: 'Transaction 69',
    amount: 54959,
    fromAccount: 'account_5',
    toAccount: 'account_4',
    transactionDate: '2023-09-22',
  },
  {
    transactionId: 'transaction_70',
    description: 'Transaction 70',
    amount: 42850,
    fromAccount: 'account_4',
    toAccount: 'account_6',
    transactionDate: '2023-10-29',
  },
  {
    transactionId: 'transaction_71',
    description: 'Transaction 71',
    amount: 36853,
    fromAccount: 'account_3',
    toAccount: 'account_1',
    transactionDate: '2023-10-21',
  },
  {
    transactionId: 'transaction_72',
    description: 'Transaction 72',
    amount: 62058,
    fromAccount: 'account_3',
    toAccount: 'account_4',
    transactionDate: '2023-01-27',
  },
  {
    transactionId: 'transaction_73',
    description: 'Transaction 73',
    amount: 13821,
    fromAccount: 'account_3',
    toAccount: 'account_6',
    transactionDate: '2023-09-20',
  },
  {
    transactionId: 'transaction_74',
    description: 'Transaction 74',
    amount: 66158,
    fromAccount: 'account_4',
    toAccount: 'account_6',
    transactionDate: '2023-04-11',
  },
  {
    transactionId: 'transaction_75',
    description: 'Transaction 75',
    amount: 67125,
    fromAccount: 'account_3',
    toAccount: 'account_1',
    transactionDate: '2023-01-10',
  },
  {
    transactionId: 'transaction_76',
    description: 'Transaction 76',
    amount: 66549,
    fromAccount: 'account_3',
    toAccount: 'account_6',
    transactionDate: '2023-04-29',
  },
  {
    transactionId: 'transaction_77',
    description: 'Transaction 77',
    amount: 90736,
    fromAccount: 'account_3',
    toAccount: 'account_2',
    transactionDate: '2023-05-01',
  },
  {
    transactionId: 'transaction_78',
    description: 'Transaction 78',
    amount: 89276,
    fromAccount: 'account_5',
    toAccount: 'account_1',
    transactionDate: '2023-03-07',
  },
  {
    transactionId: 'transaction_79',
    description: 'Transaction 79',
    amount: 12319,
    fromAccount: 'account_3',
    toAccount: 'account_2',
    transactionDate: '2023-06-19',
  },
  {
    transactionId: 'transaction_80',
    description: 'Transaction 80',
    amount: 77642,
    fromAccount: 'account_4',
    toAccount: 'account_3',
    transactionDate: '2023-05-12',
  },
  {
    transactionId: 'transaction_81',
    description: 'Transaction 81',
    amount: 52252,
    fromAccount: 'account_4',
    toAccount: 'account_2',
    transactionDate: '2023-06-21',
  },
  {
    transactionId: 'transaction_82',
    description: 'Transaction 82',
    amount: 28599,
    fromAccount: 'account_4',
    toAccount: 'account_1',
    transactionDate: '2023-08-05',
  },
  {
    transactionId: 'transaction_83',
    description: 'Transaction 83',
    amount: 40449,
    fromAccount: 'account_1',
    toAccount: 'account_3',
    transactionDate: '2023-03-20',
  },
  {
    transactionId: 'transaction_84',
    description: 'Transaction 84',
    amount: 20449,
    fromAccount: 'account_5',
    toAccount: 'account_6',
    transactionDate: '2023-06-23',
  },
  {
    transactionId: 'transaction_85',
    description: 'Transaction 85',
    amount: 82753,
    fromAccount: 'account_2',
    toAccount: 'account_3',
    transactionDate: '2023-06-27',
  },
  {
    transactionId: 'transaction_86',
    description: 'Transaction 86',
    amount: 51614,
    fromAccount: 'account_5',
    toAccount: 'account_3',
    transactionDate: '2023-10-22',
  },
  {
    transactionId: 'transaction_87',
    description: 'Transaction 87',
    amount: 63991,
    fromAccount: 'account_4',
    toAccount: 'account_3',
    transactionDate: '2023-09-27',
  },
  {
    transactionId: 'transaction_88',
    description: 'Transaction 88',
    amount: 23746,
    fromAccount: 'account_4',
    toAccount: 'account_5',
    transactionDate: '2023-03-13',
  },
  {
    transactionId: 'transaction_89',
    description: 'Transaction 89',
    amount: 53588,
    fromAccount: 'account_1',
    toAccount: 'account_2',
    transactionDate: '2023-09-15',
  },
  {
    transactionId: 'transaction_90',
    description: 'Transaction 90',
    amount: 31825,
    fromAccount: 'account_4',
    toAccount: 'account_6',
    transactionDate: '2023-04-23',
  },
  {
    transactionId: 'transaction_91',
    description: 'Transaction 91',
    amount: 97891,
    fromAccount: 'account_2',
    toAccount: 'account_6',
    transactionDate: '2023-07-07',
  },
  {
    transactionId: 'transaction_92',
    description: 'Transaction 92',
    amount: 42273,
    fromAccount: 'account_1',
    toAccount: 'account_6',
    transactionDate: '2023-07-27',
  },
  {
    transactionId: 'transaction_93',
    description: 'Transaction 93',
    amount: 86980,
    fromAccount: 'account_2',
    toAccount: 'account_6',
    transactionDate: '2023-05-19',
  },
  {
    transactionId: 'transaction_94',
    description: 'Transaction 94',
    amount: 3511,
    fromAccount: 'account_1',
    toAccount: 'account_5',
    transactionDate: '2023-08-29',
  },
  {
    transactionId: 'transaction_95',
    description: 'Transaction 95',
    amount: 85601,
    fromAccount: 'account_1',
    toAccount: 'account_5',
    transactionDate: '2023-08-08',
  },
  {
    transactionId: 'transaction_96',
    description: 'Transaction 96',
    amount: 4334,
    fromAccount: 'account_6',
    toAccount: 'account_5',
    transactionDate: '2023-08-21',
  },
  {
    transactionId: 'transaction_97',
    description: 'Transaction 97',
    amount: 57040,
    fromAccount: 'account_6',
    toAccount: 'account_1',
    transactionDate: '2023-09-08',
  },
  {
    transactionId: 'transaction_98',
    description: 'Transaction 98',
    amount: 23729,
    fromAccount: 'account_3',
    toAccount: 'account_4',
    transactionDate: '2023-01-29',
  },
  {
    transactionId: 'transaction_99',
    description: 'Transaction 99',
    amount: 57360,
    fromAccount: 'account_4',
    toAccount: 'account_2',
    transactionDate: '2023-01-25',
  },
  {
    transactionId: 'transaction_100',
    description: 'Transaction 100',
    amount: 80698,
    fromAccount: 'account_3',
    toAccount: 'account_4',
    transactionDate: '2023-08-11',
  },
];
